//Doesn't link html
let age = prompt("อายุของคุณ :")
if (age == 12) {
    console.log("ไปเรียน ป.6 นะ")
}
else if (age < 12) {
    console.log("คุณยังไม่ใกล้มัธยม สู้ๆนะ")
}
else if (age == 13) {
    console.log("ไปเรียน ม.1 นะ")
}
else if (age == 14) {
    console.log("ไปเรียน ม.2 นะ")
}
else if (age == 15) {
    console.log("ไปเรียน ม.3 นะ")
}
if (age >= 19) {
    console.log("คุณจบมัธยมแล้ว !!")
}
else if (age > 15) {
    console.log("ขึ้น ม.ปลาย แล้ว!!")
}