console.log("Hello Pathomphum")
console.log("Hello world")
alert("Hello Art")

var name = "Pathomphum"
console.log(name)
console.log(name)
name = "Pop"
console.log(name)
name = "James"
console.log(name)

var firstname = "Pathomphum"
var lastname = "Srijan"
console.log(firstname)
console.log(lastname)
// alert(firstname)

var age = 17
console.log(typeof 17.25)
console.log(typeof name)
console.log(typeof false)
console.log(2 + 3.14)//ระวังทศนิยม//
console.log("Art " + "Hello world")
console.log("Art " - "Hello world")//NaN = Not a number คือ sting - * / ไม่ได้
var name = "Art" + "art"
console.log(name)
var age = 17 + 27
console.log(age)
var age = 2 + 2 * 2
console.log(age)
// order of operations () ยกกำลัง * / + - 
var age = (4 + 2 * 2 / 2 * 2 + 4 + 1 - 5 + 19) + 91
console.log(age)
var x = 20
{
    var x = 100
    let y = 15
    console.log(y)
}
console.log(x)