//Doesn't link html
console.log(1 == 1);
console.log(2 == 2)
console.log(3 == 3)
console.log(4 == "4")
console.log(5 == 6)

console.log("6" === "6")
console.log("Hello" == "Hello")
console.log("Hello" === "Hello")
console.log(4 === "4")

console.log("4" != "4")
console.log("hello" != "Hello")
console.log("4" != 4)
console.log("4" !== 4)

console.log(10 > 5)
console.log(5 < 10)
console.log(9 >= 10)
console.log(10 <= 10)
console.log(9.9 >= 9.99)
console.log(10 + 10 <= 20)